### ISSUE TITLE
DK: missing Term attribute in meta.tsv 

### ISSUE THREAD

**Issue by boevkoski** [clarin-eric/ParlaMint#711] opened 2023-07-19 11:27 UTC
Missing Term attribute in meta.tsvs. 

![image](https://github.com/clarin-eric/ParlaMint/assets/81616849/2eefc4c7-df41-4c4f-80ce-41bbe2dc38f0)

Denmark has had four terms since 2014 (the first ParlaMint.DK entry):

2011 - 2015 - https://en.wikipedia.org/wiki/2011_Danish_general_election
2015 - 2019 - https://en.wikipedia.org/wiki/2015_Danish_general_election
2019 - 2022 - https://en.wikipedia.org/wiki/2019_Danish_general_election
November 2022 (current, not in ParlaMint) -  https://en.wikipedia.org/wiki/2022_Danish_general_election

**Comment by TomazErjavec** [comment] 2023-07-19 11:57
This one is for @BartJongejan, but he never accepted the invite so I can't assign the issue to him; re-issued invite.
The problem is that DK:

* does not have defined terms at all in their corpus root TEI header
* it then (of course) also does not make reference to them in the meeting elements in the corpus components

Both these things are needed for components to be assigned to a term in TSVs and also in the concordancers. 
Surprisingly nobody noticed this before, thanks @boevkoski! Should be fixed for 3.1.

**Comment by BartJongejan** [comment] 2023-09-06 12:21
Hi,
We have now corrected the listOrg and an example file to include "term". As far as we can see, it validates.
It differs a little from eg. the British data, since we do not refer to different "parliaments" in Denmark, only to different governments and different parliamentary years. 
Before changing all data, please confirm that it is ok.

**Comment by TomazErjavec** [comment] 2023-09-07 14:38
@BartJongejan thanks for the examples:
* I think all other corpora have the "terms" inside the "parliament" organisation, then again, if DK is different and you prefer to keep it under "government" I think that should be ok too, i.e. in the concordancers you will still have terms marked. But I need to run the script to be 100% certain. However, even if it turns out I am wrong, I think I can correct the script to do what needs to be done - in short, you can leave it as it is in the attached listOrg file.
* In the example component file you have:
```
<meeting corresp="#FT" ana="#parla.term #FT.14">Regeringen Helle Thorning-Schmidt II</meeting>
<meeting n="20141" ana="#parla.session">20141</meeting>
<meeting n="1" ana="#parla.meeting">M1</meeting>
```
For the concordancer, I am taking the value of `@n` as the label for the term/session/meeting as it seems a convenient and short langauge-independnet label. So, could you add this attribute also to term? I'm not quite sure what it can be, because the other `meeting/@n` are numeric, but this one isn't. The attribute value can here be any string, still, maybe nice to leave it language independent. How about the range of years? e.g.
```
<meeting corresp="#FT" ana="#parla.term #FT.14" n="2014-2015">Regeringen Helle Thorning-Schmidt II</meeting>
``` 
If you agree, pls. annotate the corpus like this. But I would close the issue once I have in fact processed your corpus and checked that all is ok with the terms.

**Comment by TomazErjavec** [comment] 2023-10-20 17:29
This has indeed be corrected both in the TEI source and derived formats, e.g. https://www.clarin.si/ske-beta/#text-type-analysis?corpname=parlamint40_dk&wlminfreq=1&wlicase=1&include_nonwords=1&showresults=1&wlnums=frq&wlattr=speech.term

So, thanks for your work & closing.

**Closed by TomazErjavec** 2023-10-20 17:29 UTC
Labels: bug
