### ISSUE TITLE
Government affiliation not found by validation

### ISSUE THREAD

**Issue by 5roop** [clarin-eric/ParlaMint#398] opened 2022-10-27 11:53 UTC
Dear all, 

I compiled the Croatian data in TEI and the only validation error I can't get rid of is:

```ERROR[10] ParlaMint-HR: government-role organisation without affiliation: #government.HR```

The organisation in question is defined in the root TEI as
```
<listOrg>
                    <org xml:id="government.HR" role="government">
                        <orgName xml:lang="hr" full="yes">Vlada Republike Hrvatske</orgName>
                        <orgName xml:lang="en" full="yes">Government of the Republic of Croatia</orgName>
                        <event from="1990-05-30">
                            <label xml:lang="en">existence</label>
                        </event>
                    </org>
...
```

The data is on [my fork](https://github.com/5roop/ParlaMint/tree/data-HR/Data/ParlaMint-HR), the validation was run with `make validate-parlamint-HR`. What could be the cause for this?

**Comment by TomazErjavec** [comment] 2022-10-27 13:15
This is an interesting situation, it means that the particular organisation (here the government) has no persons affiliated with it, so it is in effect a "dead" organisation. On the other hand, we require the government organisation to exists.

As far as I understand from  #227 only ministers (incl. the prime minister) and deputyMinisters (cf. https://github.com/clarin-eric/ParlaMint/issues/245#issuecomment-1138570993, and aso note deputyMinister is missing from the Figure in #227) ) are members of the government. @matyaskopp, is this true?

At this point, we do not yet require ministers to be marked-up in the corpus. Which then means that the primer minister *must* be marked up as such (or presumably, president where they don't have prime ministers), even though this has not so far been a requirement either, or that this ERROR is in fact not an error, but should just be a WARNING. @matyaskopp, what do you think?

@5roop, as far as your example goes, I note that you are missing the government terms (i.e. the `listEvent/event` elements) in your government organisation, cf. the [Guidelines](https://clarin-eric.github.io/ParlaMint/#sec-government).

**Comment by 5roop** [comment] 2022-10-28 06:56
Thanks, @TomazErjavec, I added government terms in the [latest commit](https://github.com/5roop/ParlaMint/commit/90bff661edd17c8fa43fc5b5efc996646fb1dfbb) with non-overlapping dates and the validation does not raise errors anymore.

**Comment by matyaskopp** [comment] 2022-10-28 11:06
> As far as I understand from #227 only ministers (incl. the prime minister) and deputyMinisters (cf. #245 (comment), and aso note deputyMinister is missing from the Figure in #227) ) are members of the government. @matyaskopp, is this true?

yes. and deputy prime ministers -> `deputyHead` role

> At this point, we do not yet require ministers to be marked-up in the corpus. Which then means that the primer minister must be marked up as such (or presumably, president where they don't have prime ministers), even though this has not so far been a requirement either, or that this ERROR is in fact not an error, but should just be a WARNING. @matyaskopp, what do you think?

I thought we required encoded ministers. I am a bit worried to do the "ERROR->WARN" change in this situation - we don't have any other validation for a release, so we can overlook missing ministers.

**Comment by TomazErjavec** [comment] 2022-10-28 12:18
> I thought we required encoded ministers. 
We do, just not quite yet, as we haven't added this info yet. But you are right:

> I am a bit worried to do the "ERROR->WARN" change in this situation - we don't have any other validation for a release, so we can overlook missing ministers.

Yes, best leave it as an ERROR.

I am still a bit confused, as @5roop writes:
> I added government terms ... and the validation does not raise errors anymore.

which seems strange to me, as I though the errors were caused by nobody being associated with the government org, and government terms have nothing to do with this. Except if @5roop also associated some persons (e.g. the prime minister) with the gov'ment?

**Comment by 5roop** [comment] 2022-10-28 12:28
> Except if @5roop also associated some persons (e.g. the prime minister) with the gov'ment?
No, for now I only have data for MPs. I'll try and find a neat source for the ministers and include them too.

**Comment by TomazErjavec** [comment] 2022-10-28 12:38
> > Except if @5roop also associated some persons (e.g. the prime minister) with the gov'ment?
> No, for now I only have data for MPs. I'll try and find a neat source for the ministers and include them too.

OK, great, but note that while you can enter them directly, we planned to do it via TSVs, as that might be easier, cf. #194.
Also, there is the plan to do it centrally, i.e. that @jureskubic would do it for all parliaments, once we get that far.

@matyaskopp, so, I am still confused why the error message dissapeared?

**Comment by 5roop** [comment] 2022-10-28 12:50
Uf, checked again, and the error is still there.

For some reason I can't redirect the output to a file or grep it, and I missed it last time when manually scrolling through the logs.

**Comment by TomazErjavec** [comment] 2022-10-28 12:52
OK, that is a relief in a way, at least we know what is going on. So, as mystery is solved I am closing this issue.

**Closed by TomazErjavec** 2022-10-28 12:52 UTC
Labels: bug
