### ISSUE TITLE
ParlaMint.ana 2.0: redirection to KonText is not working

### ISSUE THREAD

**Issue by matyaskopp** [clarin-eric/ParlaMint#103] opened 2021-08-17 08:21 UTC
**ParlaMint.ana 2.0 is not accesible in Kontext**, but button exists in repository: http://hdl.handle.net/11356/1405
![image](https://user-images.githubusercontent.com/5867995/129688362-cfb0a059-cee2-479c-84a4-82f9b562d5eb.png)

When clicking on "Czech", a new browser tab opens: https://www.clarin.si/user/loginx?redirectTo=https://www.clarin.si/kontext/first_form?corpname=parlamint20_cz
and returns error 404

When I am logged in with my university account (cuni.cz), this appears:
![image](https://user-images.githubusercontent.com/5867995/129690317-e7de1b70-2a8c-40dd-86f5-93c100138969.png)
It is more informative but still strange

**Comment by TomazErjavec** [comment] 2021-08-17 09:26
Are you sure this is not something related to your university?
Namely, the link that is under the KonText service in the repository entry is (for CZ) simply https://www.clarin.si/kontext/first_form?corpname=parlamint21_cz, it has no redirections. And, if I select the KonText CZ corpus, everything works fine (and I am not at IJS at present). It also works regardless of whether I am logged into the repository or not. 
So, I can't reproduce your error.

**Comment by matyaskopp** [comment] 2021-08-17 09:33
The problem is in version **2.0** - I have tried to use it (by mistake).

**Comment by katjameden** [comment] 2021-08-17 09:34
Hi, just an observation. 
I was able to reproduce the error - the problem is not in the 2.1 version, but in the 2.0. Since the corpus is no longer available on KonText (it has been replaced by the 2.1 version), the link to the KonText integration returns 404 error. (https://www.clarin.si/kontext/first_form?corpname=parlamint20_cz) It does so not only for the CZ, but also for all other corpora.
(In contrast, the integration to NoSketch works fine, as the 2.0 version is still available on NoSketch - https://www.clarin.si/noske/run.cgi/corp_info?corpname=parlamint20_cz&struct_attr_stats=1) 

I suggest that we disable integration for KonText for the 2.0 version (so, disable the connection in Services on repo)

**Comment by TomazErjavec** [comment] 2021-08-17 09:38
Ah, sorry, V2.0. I agree with Katja, would it be ok if I just removed the intergration with KonText? People should use 2.1 anyway, and 2.0 will remain accessible via noSketch, which was used in DHH.

**Comment by matyaskopp** [comment] 2021-08-17 09:43
@TomazErjavec, We should be very careful when we disable old data from services. If someone cites a URL to query - this link will be broken!

**Comment by TomazErjavec** [comment] 2021-08-17 09:52
> We should be very careful when we disable old data from services. If someone cites a URL to query - this link will be broken!
Indeed we (i.e. I) should, sorry about this. Disabled KonText from 2.0 now, closing.

**Closed by TomazErjavec** 2021-08-17 09:52 UTC
Labels: bug
